name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [13.8.0]
      max-parallel: 1 # to ensure windows failure can prevent ubuntu from publishing package
    runs-on: ${{ matrix.os }}
    name: node ${{ matrix.node }} on ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        run: npm run eslint-check
      - name: code format
        run: npm run prettier-check
      - name: testing
        run: npm run test-with-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: upload coverage
        run: npm run upload-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: pull request size impact
        if: github.event_name == 'pull_request' && runner.os == 'Linux' # runner check to run it once
        run: |
          git checkout -f $GITHUB_BASE_REF
          npm install
          npm run dist
          node ./.github/generate-size-snapshot.js ../snapshot.base.json
          git checkout -f $GITHUB_HEAD_REF
          npm install
          npm run dist
          node ./.github/generate-size-snapshot.js ../snapshot.head.json
          node ./.github/report-size-impact ../snapshot.base.json ../snapshot.head.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish package
        if: github.event_name == 'push' && runner.os == 'Linux' # runner check to run it once
        run: node ./.github/publish-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ensure github release
        if: github.event_name == 'push' && runner.os == 'Linux' # runner check to run it once
        run: node ./.github/ensure-github-release-for-package.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
