name: size-impact

on: pull_request

jobs:
  size-impact:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [13.8.0]
    runs-on: ${{ matrix.os }}
    name: node ${{ matrix.node }} on ${{ matrix.os }}
    env:
      CI: true
      SIZE_IMPACT_DIR: .github/size-impact
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Dump RUNNER_WORKSPACE
        run: echo "$RUNNER_WORKSPACE"
      - name: npm config
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: install size-impact
        run: |
          cd $SIZE_IMPACT_DIR
          npm install
          cd $RUNNER_WORKSPACE
          cp -r $SIZE_IMPACT_DIR ../size-impact-copy
      - name: generate base snapshot
        run: |
          git checkout -f $GITHUB_BASE_REF
          rm -r $SIZE_IMPACT_DIR
          mv ../size-impact-copy $SIZE_IMPACT_DIR
          npm install
          npm run dist
          node $SIZE_IMPACT_DIR/generate-size-snapshot.js ../snapshot.base.json
      - name: generate head snapshot
        run: |
          git checkout -f $GITHUB_HEAD_REF
          rm -r $SIZE_IMPACT_DIR
          mv ../size-impact-copy $SIZE_IMPACT_DIR
          npm install
          npm run dist
          node $SIZE_IMPACT_DIR/generate-size-snapshot.js ../snapshot.head.json
      - name: report size impact
        run: node $SIZE_IMPACT_DIR/report-size-impact.js ../snapshot.base.json ../snapshot.head.json
