name: size-impact

on:
  pull_request:
    # In theory it would be more efficient to enable this workflow only
    # if certain file changes (the one that could impact dist/ files)
    # In practice humans will wonder why the workflow did not run.
    # paths:
    #   - "index.js"
    #   - "src/**"

jobs:
  size-impact:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [13.12.0]
    runs-on: ${{ matrix.os }}
    name: size impact
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm config
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Please note || echo "{}" > ../snapshot.base.json
      # It means we fallback on an empty snapshot when left command fails.
      # It exists in case the base branch does not contains size-impact files.
      # Happens at least when a pull request introduces
      # @jsenv/github-pull-request-filesize-impact to a repository for the first time.
      - name: generate base snapshot
        run: |
          git checkout -f $GITHUB_BASE_REF
          npm install
          npm run dist
          node ./.github/size-impact/generate-size-snapshot.js ../snapshot.base.json || echo "{}" > ../snapshot.base.json
      - name: generate head snapshot
        run: |
          git checkout -f $GITHUB_HEAD_REF
          npm install
          npm run dist
          node ./.github/size-impact/generate-size-snapshot.js ../snapshot.head.json
      - name: report size impact
        run: node ./.github/size-impact/report-size-impact.js ../snapshot.base.json ../snapshot.head.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
